<?php
/*
 * citeproc-php
 *
 * @link        http://github.com/seboettg/citeproc-php for the source repository
 * @copyright   Copyright (c) 2016 Sebastian Böttger.
 * @license     https://opensource.org/licenses/MIT
 */

namespace Seboettg\CiteProc\Test\Locale;

use Seboettg\CiteProc\Config;
use PHPUnit\Framework\TestCase;
use Seboettg\CiteProc\Exception\CiteProcException;
use Seboettg\CiteProc\Locale\Locale;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:29:49.
 */
class LocaleTest extends TestCase
{
    /**
     * @var Locale
     */
    protected $object;

    public function testFilterTerms()
    {
        $term1 = $this->object->filter("terms", "no date");
        $term2 = $this->object->filter("terms", "no date", "short");
        static::assertEquals("ohne Datum", $term1->{'single'});
        static::assertEquals("o. J.", $term2->{'single'});
    }

    /**
     * @throws CiteProcException
     */
    protected function setUp()
    {
        $this->object = Locale::factory(Config\Locale::DE_DE());
    }
}
